# Generated by Django 4.1.1 on 2023-04-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_nrgp_entry_nrgp_approve_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rgp_entry',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='rgp_entry',
            name='inward_receiver',
        ),
        migrations.RemoveField(
            model_name='rgp_entry',
            name='outward_sender',
        ),
        migrations.RemoveField(
            model_name='rgp_entry',
            name='rgp_created',
        ),
        migrations.RemoveField(
            model_name='rgp_entry',
            name='verifier',
        ),
        migrations.DeleteModel(
            name='Nrgp_entry',
        ),
        migrations.DeleteModel(
            name='Rgp_entry',
        ),
        migrations.DeleteModel(
            name='User_rgp',
        ),
    ]
