# Generated by Django 4.1.1 on 2023-07-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_contact_us_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=100)),
                ('ce', models.CharField(max_length=100)),
                ('dp', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveIntegerField()),
            ],
        ),
    ]
